server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.pagination.default-page=0
app.pagination.default-size=5
app.pagination.default-sort=id
app.pagination.default-direction=asc

management.endpoints.web.exposure.include=health,info,caches,metrics
management.endpoint.caches.enabled=true
logging.level.org.springframework.cache=TRACE
